lemonbar:
    offset:
        x: 0
        y: 0
    dimensions:
        w: 3200
        h: 40

    fonts:
        -
            str: 'Hack:size=10'
            offset: -8
        -
            str: 'Knack Nerd Font Mono:size=16'
            offset: 1

    xresources: False
    colors:
        foreground: '#fff'
        background: '#000'
        highlights: '#fff'

    underline_thickness: 2
    update_interval: 0.5


blocks:
    left:
        WorkspacesDots:
            swap: True
            margin: 0
            padding: 2
            icons:
                empty: '○'
                nonempty: '●'
                visible: '●'
            underline: '#000'
        Music:
            icon: '▶'
            margin: 2


    center:
        Clock:
            layout: '%a, %d %b, %_H:%M'

    right:
        Wifi:
            icon: ''
            interface: 'wlp1s0'
            margin: 2
        Volume:
            icon: ''
            swap: True
            interval: 1
            padding: [2, 1]
        Memory:
            icon: ''
            swap: True
            interval: 5
            padding: 1
        Battery:
            icons: 
                charging: ''
                discharging: 
                    - ''
                    - ''
                    - ''
                    - ''
                    - ''
            swap: True
            power_supply: 'BAT1'
            padding: [1, 2]
