lemonbar:
    offset:
        x: 0
        y: 0
    dimensions:
        w: 3200
        h: 40

    fonts:
        -
            str: 'Hack:size=10'
            offset: -8
        -
            str: 'Knack Nerd Font Mono:size=16'
            offset: 1

    xresources: False
    colors:
        foreground: '#fff'
        background: '#000'
        highlights: '#fff'

    underline_thickness: 2
    update_interval: 0.5


blocks:
    left:
        WorkspacesDots:
            swap: True
            margin: 0
            padding: 2
            icons:
                empty: 'o'
                nonempty: '0'
                visible: 'x'
            underline: '#000'
        Music:
            icon: 'p'
            margin: 2


    center:
        Clock:
            layout: '%d %b %Y %H:%M:%S'

    right:
        Wifi:
            interface: 'wlp1s0'
        Volume:
            swap: True
            interval: 1
            padding: [2, 1]
        Memory:
            swap: True
            interval: 5
        Battery:
            swap: True
            power_supply: 'BAT1'
            padding: [1, 2]
